### ISSUE TITLE
Provide binary artifacts through Releases?

### ISSUE THREAD

**Issue by kokes** [tobert/pcstat#25]
Perhaps [Releases](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) could be used to distribute pcstat artifacts. It would be a more obvious place to look, a more credible place than "an old branch", and, last but not least, would allow for new os/architecture combos - notably arm64 has gained prominence in the recent years, so that would be helpful.

My dummy Makefile could build at least some of these targets - though not linux/amd64, but that's due to the older x/sys and the hardcoded `SYS_SETNS`, which is now included for many arches in x/sys natively)... but that's all for a separate ticket.

```
.PHONY: dist

BUILD_OS ?= linux darwin
BUILD_ARCH ?= amd64 386 arm64

dist:
	mkdir -p dist
	@for os in $(BUILD_OS) ; do \
		for arch in $(BUILD_ARCH); do \
			echo "Buidling" $$arch $$os; \
			binpath="dist/pcstat-$$os-$$arch"; \
			CGO_ENABLED=0 GOARCH=$$arch GOOS=$$os go build -o $$binpath ./pcstat; \
		done \
	done
	(cd dist; shasum -a 256 * > sha256sums.txt)
```

(perhaps gzipping would be nice as well)

**Comment by tobert** [comment]
Done :) Again, thank you for your patience. https://github.com/tobert/pcstat/releases/tag/v0.0.1

**Comment by kokes** [comment]
Great stuff!
