### ISSUE TITLE
Ignore zero length files

### ISSUE THREAD

**Issue by eribeiro** [tobert/pcstat#8]
When I was using pcstat to analyse Solr index files, the write.lock index file would sometimes be empty. It would be nice if pcstat could just ignore those files instead of throwing an exception and aborting execution, maybe throwing a warning instead. https://github.com/tobert/pcstat/blob/master/pcstatus.go#L59-L61 

ps: it has been a handy tool to investigate DSE Search performance problems. ;)

**Comment by tobert** [comment]
That was a particularly silly error on my part. Fixed in f5eaebdb412c7b74d3e14c46d3d535a1c7525d0b
