### ISSUE TITLE
Docs are out of data

### ISSUE THREAD

**Issue by millerjp** [tobert/pcstat#9]
pcsatst Command-line arguments no longer match the docs e.g. histo

**Comment by tobert** [comment]
Hmm. Can you provide an example or a screenshot please? Looks OK to me but I wrote the silly thing so maybe I can't see the omission.

atobey@arch $ pcstat -histo /bin/z*
/bin/zcat             1 ▁
/bin/zcmp             1 ▁
/bin/zdiff            2 ▁▁
/bin/zdump            5 ▁▁▁▁▁
